### PR TITLE
Performance increases, Code cleanup, and .NET Task API implementation

### PR DESCRIPTION
**Pull request by steveadoo32**
Removed all the code for multithreading and replaced it with the Task API. It's way easier to maintain and will handle any asynchronous code way better.

Cleaned up the codebase(still cleaning up) and added a controller for the MainWindow so we can separate our logic from the view. This is still being worked on but it's good enough for now.

CPU usage should decrease a lot(i noticed some changes over the weekend that also decreased CPU usage) and memory should decrease a little bit.

### CODE REVIEW

**Comment by psouza4** [comment]
Did you see that I already released an optimized version 8.2 that reduces
CPU usage?

Additionally, what makes the Task API better and what kind of licensing
does it carry?

**Comment by Codeusa** [comment]
Hi @steveadoo32 thanks for the contribution, I'm going to assign this pull to @psouza4 but I am curious myself to hear more about the Task API.

**Comment by steveadoo32** [comment]
I saw the update and it required a lot of code that this release doesn't need, so it simplifies the codebase significantly. 

The task api is included with C# so there's no additional licenses. You guys are using  4.0 though so it requires a support library from Microsoft if we want to use async and await modifiers. 

The task api will simplify any kind of multithreading greatly because we can use async and await and let's us easily maintain the app. There are also a lot of optimizations done in the background when creating and running tasks that we don't have to worry about.

**Comment by steveadoo32** [comment]
I saw your edit. Other developers shouldn't need anything. The package is from nuget so it will be downloaded automatically.

**Comment by psouza4** [comment]
Fantastic work, Steve.

We've made some changes that weren't entirely compatible recently, minor stuff really, and merged the bulk of your updates manually into the master branch, mostly using your implementation of the .NET Task framework to handle threading (although there are still instances in the code where temporary threads with timeouts are being used)

We chose not to merge some style changes you proposed, such as renaming /Forms to /View and other minor things, just to make it easier for us to maintain, but we felt that the bulk of your updates were useful and a great improvement to the project.

Thank you for your contribution and efforts!

**Pull request closed without merging**
