### PR TITLE
Added Russian localization

### PR DESCRIPTION
**Pull request by Svetomech**

### CODE REVIEW

**Comment by Svetomech** [comment]
Didn't find a convenient way to translate buttons'/labels'/etc text. Is there one?

**Comment by Codeusa** [comment]
Thank you for your contribution!

**Comment by Codeusa** [comment]
Hi @Svetomech 


Would you mind moving your translation over to [the new format](https://github.com/Codeusa/Borderless-Gaming/issues/328)?

**Comment by Svetomech** [comment]
Sure thing.

**Pull request merged**
